spring.application.name=expense-approval-system

server.port=${PORT:8084}

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION:86400000}

logging.level.com.siva.expense_approval_system.application.impl=INFO
logging.level.org.springframework.security=INFO

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.baseline-version=1